server:
  port: 3000
  base-url: /ejemplo_noticias
db:
  description: base de prueba
  host: localhost
  port: 5432
  database: ejemplo_noticias_db
  schema: ejemplo_noticias
  user: ejemplo_noticias_admin
  password: cambiar_esta_clave
install:
  dump:
    db:
      owner: ejemplo_noticias_owner
client-setup: 
  lang: es
devel:
  delay: 0
log:
  db:
    on-demand: true